version: '3'

services:
  redis:
    image: "redis:alpine"
  db:
    image: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  web:
    build: docker/web
    command: python3 -m flask run
    volumes:
      - ./backend:/backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment: 
      FLASK_APP: /backend/app.py
      FLASK_RUN_HOST: "0.0.0.0"
  