version: '3'

services:
  redis:
    image: "redis:alpine"
  db:
    build: docker/db
    ports:
      - "4000:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
  backend:
    build: docker/backend
    command: ["./wait-for-it.sh", "db:5432", "--", "python3", "-m", "flask", "run"]
    volumes:
      - ./backend:/backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment: 
      FLASK_APP: /backend/app.py
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_ENV: development
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/app:/frontend/app 
      # - ./frontend/app/node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 2001:2001
      - 443:443
    depends_on:
      - frontend
      - backend